"""Add Account model and transaction relations

Revision ID: 06193dea4dfd
Revises: e7b4ff5f33ce
Create Date: 2026-06-15 15:27:39.743348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06193dea4dfd'
down_revision: Union[str, Sequence[str], None] = 'e7b4ff5f33ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('name', sqlmodel.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.AutoString(), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('is_on_budget', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_budget_id'), ['budget_id'], unique=False)


    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transfer_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transaction_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_transfer_id'), ['transfer_id'], unique=False)
        batch_op.create_foreign_key('fk_transaction_account_id_account', 'account', ['account_id'], ['id'])
        batch_op.create_foreign_key('fk_transaction_transfer_id_account', 'account', ['transfer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_transfer_id_account', type_='foreignkey')
        batch_op.drop_constraint('fk_transaction_account_id_account', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transaction_transfer_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_account_id'))
        batch_op.drop_column('transfer_id')
        batch_op.drop_column('account_id')


    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_budget_id'))

    op.drop_table('account')
    # ### end Alembic commands ###
