"""initial_schema

Revision ID: 1c101542ee75
Revises: 
Create Date: 2026-03-28 22:37:28.995988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c101542ee75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgetmember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_budget_budget_id'), ['budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_budget_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_budget_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_budget_year'), ['year'], unique=False)

    op.create_table('transaction',
    sa.Column('merchant_name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_budget_id'), ['budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_merchant_name'), ['merchant_name'], unique=False)

    op.create_table('budget_category_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_budget_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['monthly_budget_id'], ['monthly_budget.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monthly_budget_id', 'category_id', name='uq_budget_category_limit')
    )
    with op.batch_alter_table('budget_category_limit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_category_limit_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_category_limit_monthly_budget_id'), ['monthly_budget_id'], unique=False)

    op.create_table('receiptscan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receiptscan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receiptscan_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_receiptscan_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('transactionline',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactiontaglink',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactiontaglink')
    op.drop_table('transactionline')
    with op.batch_alter_table('receiptscan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receiptscan_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_receiptscan_content_hash'))

    op.drop_table('receiptscan')
    with op.batch_alter_table('budget_category_limit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_category_limit_monthly_budget_id'))
        batch_op.drop_index(batch_op.f('ix_budget_category_limit_category_id'))

    op.drop_table('budget_category_limit')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_merchant_name'))
        batch_op.drop_index(batch_op.f('ix_transaction_budget_id'))

    op.drop_table('transaction')
    with op.batch_alter_table('monthly_budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_budget_year'))
        batch_op.drop_index(batch_op.f('ix_monthly_budget_user_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_budget_month'))
        batch_op.drop_index(batch_op.f('ix_monthly_budget_budget_id'))

    op.drop_table('monthly_budget')
    op.drop_table('budgetmember')
    op.drop_table('tag')
    op.drop_table('category')
    op.drop_table('budget')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
