"""add transaction import hash

Revision ID: 20240411_import_hash
Revises: 04012e41bf32
Create Date: 2024-04-11 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20240411_import_hash'
down_revision = '04012e41bf32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('import_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_transaction_import_hash'), 'transaction', ['import_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_import_hash'), table_name='transaction')
    op.drop_column('transaction', 'import_hash')
    # ### end Alembic commands ###
