"""Add ProductCategoryCache

Revision ID: 2138c1257fac
Revises: 20260529_transactionline_is_adjustment
Create Date: 2026-05-30 01:36:32.314324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2138c1257fac'
down_revision: Union[str, Sequence[str], None] = '20260529_transactionline_is_adjustment'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_category_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_name', name='uq_user_normalized_name')
    )
    op.create_index(op.f('ix_product_category_cache_normalized_name'), 'product_category_cache', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_product_category_cache_user_id'), 'product_category_cache', ['user_id'], unique=False)
    op.create_index('ix_envelope_allocation_budget_date', 'envelope_allocation', ['budget_id', 'year', 'month'], unique=False)
    op.create_index('ix_transaction_budget_type_date', 'transaction', ['budget_id', 'type', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_budget_type_date', table_name='transaction')
    op.drop_index('ix_envelope_allocation_budget_date', table_name='envelope_allocation')
    op.drop_index(op.f('ix_product_category_cache_user_id'), table_name='product_category_cache')
    op.drop_index(op.f('ix_product_category_cache_normalized_name'), table_name='product_category_cache')
    op.drop_table('product_category_cache')
    # ### end Alembic commands ###
