"""Add category_source

Revision ID: 5d38caf49410
Revises: e7b4ff5f33ce
Create Date: 2026-06-15 13:12:00.898814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d38caf49410'
down_revision: Union[str, Sequence[str], None] = 'e7b4ff5f33ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactionline', sa.Column('category_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactionline', 'category_source')
    # ### end Alembic commands ###
