"""Add BudgetAlert table

Revision ID: 5f33e5ac5df4
Revises: fb1ef734c09d
Create Date: 2026-05-31 10:24:14.464878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f33e5ac5df4'
down_revision: Union[str, Sequence[str], None] = 'fb1ef734c09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgetalert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgetalert_budget_id'), 'budgetalert', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budgetalert_user_id'), 'budgetalert', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgetalert_user_id'), table_name='budgetalert')
    op.drop_index(op.f('ix_budgetalert_budget_id'), table_name='budgetalert')
    op.drop_table('budgetalert')
    # ### end Alembic commands ###
