"""add budget_id to transaction and fix existing data

Revision ID: 6687268e50ab
Revises: b5613ca7c88a
Create Date: 2026-04-03 03:00:19.418377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '6687268e50ab'
down_revision: Union[str, Sequence[str], None] = 'b5613ca7c88a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Create budgets for users without one
    users_without_budget = conn.execute(text("""
        SELECT u.id, u.email 
        FROM user u
        LEFT JOIN budgetmember bm ON bm.user_id = u.id
        WHERE bm.id IS NULL
    """)).fetchall()
    
    for user_id, email in users_without_budget:
        # Create budget for user
        conn.execute(text("""
            INSERT INTO budget (name, owner_id, created_at)
            VALUES (:name, :owner_id, datetime('now'))
        """), {"name": "Domowy", "owner_id": user_id})
        
        budget_id = conn.execute(text("SELECT last_insert_rowid()")).scalar()
        
        # Add user as owner of budget
        conn.execute(text("""
            INSERT INTO budgetmember (budget_id, user_id, role)
            VALUES (:budget_id, :user_id, 'owner')
        """), {"budget_id": budget_id, "user_id": user_id})
        
        # Update transactions without budget_id
        conn.execute(text("""
            UPDATE "transaction" 
            SET budget_id = :budget_id 
            WHERE uploaded_by = :user_id AND budget_id IS NULL
        """), {"budget_id": budget_id, "user_id": user_id})
    
    # Also fix any transactions that still have NULL budget_id by finding budget from budgetmember
    # This handles cases where users already have budgetmember entries
    conn.execute(text("""
        UPDATE "transaction" 
        SET budget_id = (
            SELECT bm.budget_id 
            FROM budgetmember bm 
            WHERE bm.user_id = "transaction".uploaded_by
            LIMIT 1
        )
        WHERE budget_id IS NULL AND uploaded_by IS NOT NULL
    """))
        
        # Note: category and tag tables have already been migrated in b5613ca7c88a
        # They now use budget_id instead of owner_id
        # Skip updating them here as they should already have budget_id set
    
    # Ensure the budget_id column exists (though it should from initial migration)
    try:
        # Try to add column if it doesn't exist (for fresh deployments)
        with op.batch_alter_table('transaction', schema=None) as batch_op:
            batch_op.add_column(sa.Column('budget_id', sa.Integer(), nullable=True))
    except Exception:
        # Column already exists, that's fine
        pass
    
    # Create foreign key if it doesn't exist
    try:
        with op.batch_alter_table('transaction', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_transaction_budget_id', 'budget', ['budget_id'], ['id'])
    except Exception:
        # Constraint already exists, that's fine
        pass
    
    # Create index if it doesn't exist
    try:
        with op.batch_alter_table('transaction', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_transaction_budget_id'), ['budget_id'], unique=False)
    except Exception:
        # Index already exists, that's fine
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This is a data migration, we cannot fully revert it
    # But we can drop the foreign key constraint and index
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_budget_id'))
        batch_op.drop_constraint('fk_transaction_budget_id', type_='foreignkey')
        batch_op.drop_column('budget_id')
    # ### end Alembic commands ###
