"""add budget_id to transaction

Revision ID: 6687268e50ab
Revises: b5613ca7c88a
Create Date: 2026-04-03 03:00:19.418377

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '6687268e50ab'
down_revision: Union[str, Sequence[str], None] = 'b5613ca7c88a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
