"""add keep_image to receiptscan

Revision ID: 7e0d4ea8462b
Revises: fee1dd034a04
Create Date: 2026-03-29 21:25:41.337419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0d4ea8462b'
down_revision: Union[str, Sequence[str], None] = 'fee1dd034a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop temporary table if it was left over from a failed migration attempt
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_budget_category_limit")
    with op.batch_alter_table('budget_category_limit', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_budget_category_limit', ['monthly_budget_id', 'category_id'])

    with op.batch_alter_table('receiptscan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keep_image', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receiptscan', schema=None) as batch_op:
        batch_op.drop_column('keep_image')

    with op.batch_alter_table('budget_category_limit', schema=None) as batch_op:
        batch_op.drop_constraint('uq_budget_category_limit', type_='unique')

    op.create_table('_alembic_tmp_budget_category_limit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('monthly_budget_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['monthly_budget_id'], ['monthly_budget.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monthly_budget_id', 'category_id', name=op.f('uq_budget_category_limit'))
    )
    # ### end Alembic commands ###
