"""Add category_id to Account

Revision ID: f775379c3748
Revises: 06193dea4dfd
Create Date: 2026-06-15 13:47:30.273460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f775379c3748'
down_revision: Union[str, Sequence[str], None] = '06193dea4dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_account_category_id', 'category', ['category_id'], ['id'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_budget_id'))
        batch_op.drop_constraint(batch_op.f('uq_category_name_budget'), type_='unique')

    with op.batch_alter_table('transactionline', schema=None) as batch_op:
        batch_op.drop_column('category_source')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_default_budget_id', 'budget', ['default_budget_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_default_budget_id', type_='foreignkey')

    with op.batch_alter_table('transactionline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_source', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_category_name_budget'), ['name', 'budget_id'])
        batch_op.create_index(batch_op.f('ix_category_budget_id'), ['budget_id'], unique=False)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('fk_account_category_id', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
