"""Add raw OCR data to ReceiptScan

Revision ID: fb1ef734c09d
Revises: 2138c1257fac
Create Date: 2026-05-31 08:42:58.881693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1ef734c09d'
down_revision: Union[str, Sequence[str], None] = '2138c1257fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receiptscan', sa.Column('raw_ocr_text', sa.String(), nullable=True))
    op.add_column('receiptscan', sa.Column('reconstructed_lines', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receiptscan', 'reconstructed_lines')
    op.drop_column('receiptscan', 'raw_ocr_text')
    # ### end Alembic commands ###
